export const routesConst = {
	login: '/login',
	verifyLogin: '/login/verify',
	verifyCode: '/verify/code',
	signup: '/signup',
	changeAccount: '/change/account',
	createGroup: '/create/group',
	forgotPwd: '/forgot/pwd',
	groupInfo: '/group/info',
	main: '/',
	group: '/group',
	solveTask: '/solve/task',
	createTask: '/create/task',
	deleteAccount: '/delete/account',
	updateUser: '/update/account',
}
